### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [jirmauritz/MapOfNews#6]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by jirmauritz** [comment]
Hi,
thank you for suggestion, I will take a look at that. I noticed libs around Kotlin are very alive right now, so my choice is pretty much random and I will have to consider more options in the future. Your solution looks nice though!
